apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservice
  name: app-service
spec:
  ports:
  - name: demoport
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demo-app
  type: LoadBalancer
status:
  loadBalancer: {}